### ISSUE TITLE
Shutdown after a few minutes

### ISSUE THREAD

**Issue by martinjungkunz** [PiSupply/Pi-Supply-Switch#12]
Hi there,

I have some problem with my Py-Supply On/Off Switch. On and Off work perfectly fine but the soft shutdown does not. That's not much of a problem since my main goal is to cut the power off. 

Secondly, the Pi shuts down after a few minutes when used with the Pi-Supply. It's a hard shutdown. I installed the scripts from Github so I think the problem is with the hardware. Have you ever heard of the board acting like that? 
Thank you in advance, best
Martin

**Comment by francesco-vannini** [comment]
Hey Martin,
did you check the service is running fine?
https://github.com/PiSupply/Pi-Supply-Switch#how-do-i-know-if-the-service-is-running-properly

**Comment by martinjungkunz** [comment]
Yes I did and I got the message posted in the your link

**Comment by shawaj** [comment]
It sounds like you didn't connect the flying GPIO cable between the switch and the Pi?

**Comment by martinjungkunz** [comment]
Actually i did connect it. If I don't, the Pi aborts the boot after a few seconds. In my case it works fine for about 1 to 3 minutes and then suddenly shuts down.

**Comment by shawaj** [comment]
It is likely you don't have the software correctly running then or you haven't connected the cable to the correct pin.

That's really the only two things that can cause the issue you're seeing.

**Comment by martinjungkunz** [comment]
OK, thank you. All I did was connecting the pin with the label 7 to 7 and 8 to 8 and installing via the install script. Don't know what else to do here... but perhaps I'll give it another try.

**Comment by martinjungkunz** [comment]
Hahaha... and just after I wrote my answer I re-read the readme and realized that 8 goes to 11... will try that later

**Comment by shawaj** [comment]
Awesome, let us know how you get on

**Comment by martinjungkunz** [comment]
Works perfect now. Sorry for bothering you although I just should have read more carefully

**Comment by shawaj** [comment]
No problem at all. That's what we are here for :-)
