### ISSUE TITLE
Link for the text-guide not working

### ISSUE THREAD

**Issue by h3n3b0sch** [PiSupply/Pi-Supply-Switch#18]
Hello,

Is it possible to get all the related files, guides and programs in this repository? It would be more handy and links seems to disappear over time.

Hendrie

**Comment by ChristopherRush** [comment]
@boschie Here you go - https://learn.pi-supply.com/make/pi-supply-switch-assembly-instructions/

**Comment by h3n3b0sch** [comment]
@ChristopherRush Thanks!

The link in the README.md is still wrong. Could this page be implemented in the wiki of this repository? Just to keep it all in one place...

**Comment by ChristopherRush** [comment]
I'll update the link through Github but at the moment we will not use
Githib wiki since we don't want too many duplication of the same thing.

**Comment by h3n3b0sch** [comment]
Ok, thanks!
