### ISSUE TITLE
There was a problem writing the softshut.py file Installation aborted

### ISSUE THREAD

**Issue by f4bpp** [PiSupply/Pi-Supply-Switch#19]
Hello,

I have an issue with the script installation.

I run the command 

**_curl -sSL https://pisupp.ly/piswitchcode | sudo bash_**

and get the error 

**_There was a problem writing the softshut.py file Installation aborted_**

I run this on my octoprint printer server on a raspberry Pi 3B +

Can someone help me please ?
![Error](https://user-images.githubusercontent.com/16517945/83978258-79685500-a906-11ea-90ca-81cc04f612d9.jpg)

**Comment by shawaj** [comment]
@ChristopherRush do you have an octoprint setup you can test this with?

**Comment by ryanteck** [comment]
Just quickly ran it, seems the issue is with the git clone as it fails due to recommending you don't run git as sudo which as the entire script is sudo'd then fails.

Here's the error log

```pi@octopi:~ $ curl -sSL https://pisupp.ly/piswitchcode | sudo bash
[sudo] password for pi:
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.20.1-2+deb10u1).
whiptail is already the newest version (0.52.20-8).
whiptail set to manually installed.
The following package was automatically installed and is no longer required:
  libllvm8
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Please do not run git as root, your regular user account is enough :)

If you need to run git with root rights for some other application than
what comes preinstalled on this image you can remove this sanity check:

    sudo rm /root/bin/git

You might have to restart your login session after doing that.
cp: cannot stat 'Pi-Supply-Switch/softshut.py': No such file or directory
```

Solution is likely modifying it to download the files directly maybe, or not running the entire script as root?

**Comment by shawaj** [comment]
@ryanteck maybe just run the bite that need it as root is easiest?

**Comment by f4bpp** [comment]
To Aaron, Ryan and Christopher : Many thanks for your help. 3 persons to help me I would never expected as much ! Now I'm sure one of you will find the solution. Many thanks to you !

**Comment by ChristopherRush** [comment]
@ryanteck Did you test it on your OctoPrint? Script runs fine on Raspbian.

**Comment by ryanteck** [comment]
Yeah that was on footprint.

**Comment by ChristopherRush** [comment]
@ryanteck @shawaj Aarons method seems to work. Run the script as normal user and add root to parts that require it.

**Comment by f4bpp** [comment]
Well... If I run the script as normal user, a message tell me it must be run with root privileges. The best way for me is a new script working for Octoprint.

**Comment by ChristopherRush** [comment]
@magellan-13016 Try the following `curl -sSL https://pisupp.ly/piswitchoctoprint | bash`

**Comment by f4bpp** [comment]
Dear team, you're simply the best !

Install is now complete. I suggest you to add this script on the main page of Pi Supply Switch so evey people using Octoprint can install it without any issue.

Many many many thanks to all of you.

David.
![Install Complete](https://user-images.githubusercontent.com/16517945/84025783-7152f880-a98c-11ea-8885-89c253521673.jpg)

**Comment by ivanolenichev** [comment]
Hi Aaron, @shawaj . Sorry for the off topic post. I can’t contact you by mail or other channels. Please write how you can be contacted?

**Comment by ChristopherRush** [comment]
@magellan-13016 Super, I have added it to the main readme section for OctoPrint.
