### ISSUE TITLE
Open source hardware certification

### ISSUE THREAD

**Issue by shawaj** [PiSupply/Pi-Supply-Switch#20]
Pi Supply Switch certification
![OSHW_mark_UK000019](https://user-images.githubusercontent.com/3359418/94977211-af61c280-050f-11eb-8f15-4a94fd3bdbaa.png)
[OSHW_mark_UK000019.pdf](https://github.com/PiSupply/Pi-Supply-Switch/files/5320742/OSHW_mark_UK000019.pdf)

**Comment by ChristopherRush** [comment]
![OSHW_mark_UK000019](https://user-images.githubusercontent.com/1878314/95061022-f65bdd80-06f2-11eb-9899-0029074ed2ed.png)

**Comment by ryanteck** [comment]
Can I just ask why we keep uploading images as issues rather than putting them in the repositories.

Shouldn't they be uploaded to the repo?

**Comment by shawaj** [comment]
@ryanteck main idea was to keep the repos tidy and uncluttered and then just link to the images
