### ISSUE TITLE
Softshut reboots after a while

### ISSUE THREAD

**Issue by JLGBJ** [PiSupply/Pi-Supply-Switch#21]
I have a raspberry pi 3B+, it was running ok both ON and OFF buttons were working perfect. A couple of weeks ago the OFF button started to reboot itself after approximately 3 min., it does a soft shutdown and after 3 min. reboot the PI, when pressed as second time is does a soft shutdown and stays shutdown, could it be a corrupt file? ,  I’m running Octopi.

**Comment by shawaj** [comment]
Just to check do you have the 2 pin cable connected between the pi and the switch? If so which pins are you using on the pi and the corresponding pin on the switch?

Can you also post the script you are using? Did you just use the default install method shown in the readme or something else?

Did you make any updates or changes to the software or octopi at all recently?

**Comment by JLGBJ** [comment]
Hi @shawaj, thanks for replaying, yes I have the 2 pin cable connected as per the instructions:

PiSwitch 7 <---> RPi 7
PiSwitch 8 <---> RPi 11

The script is softshut.py and it was installed as per de readme file , this is what it looks like:

#!/usr/bin/env python
# Import the modules to send commands to the system and access GPIO pins
from subprocess import call
import RPi.GPIO as GPIO
from time import sleep
# Map pin seven and eight on the Pi Switch PCB to chosen pins on the Raspberry Pi header
# The PCB numbering is a legacy with the original design of the board
PinSeven = 7
PinEight = 11
GPIO.setmode(GPIO.BOARD) # Set pin numbering to board numbering
GPIO.setup(PinSeven, GPIO.IN) # Set up PinSeven as an input
GPIO.setup(PinEight, GPIO.OUT, initial=1) # Setup PinEight as output
while (GPIO.input(PinSeven) == False): # While button not pressed
 GPIO.wait_for_edge(PinSeven, GPIO.RISING) # Wait for a rising edge on PinSeven
 sleep(0.1); # Sleep 100ms to avoid triggering a shutdown when a spike occured
sleep(2); # Sleep 2s to distinguish a long press from a short press
if (GPIO.input(PinSeven) == False):
 GPIO.output(PinEight,0) # Bring down PinEight so that the capacitor can discharge and remove power to the Pi
 call('poweroff', shell=False) # Initiate OS Poweroff
else:
 call('reboot', shell=False) # Initiate OS Reboot

No changes were made to the software or octopi. I´m running Octoprint V.1.4.2 and 
Octopi V.0.17.0

**Comment by JLGBJ** [comment]
Hi @shawaj, thanks for replaying, yes I have the 2 pin cable connected as per the instructions:

PiSwitch 7 <---> RPi 7
PiSwitch 8 <---> RPi 11

The script is softshut.py and it was installed as per de readme file , this is what it looks like:

```
#!/usr/bin/env python
#Import the modules to send commands to the system and access GPIO pins
from subprocess import call
import RPi.GPIO as GPIO
from time import sleep
#Map pin seven and eight on the Pi Switch PCB to chosen pins on the Raspberry Pi header
#The PCB numbering is a legacy with the original design of the board
PinSeven = 7
PinEight = 11
GPIO.setmode(GPIO.BOARD) # Set pin numbering to board numbering
GPIO.setup(PinSeven, GPIO.IN) # Set up PinSeven as an input
GPIO.setup(PinEight, GPIO.OUT, initial=1) # Setup PinEight as output
while (GPIO.input(PinSeven) == False): # While button not pressed
 GPIO.wait_for_edge(PinSeven, GPIO.RISING) # Wait for a rising edge on PinSeven
 sleep(0.1); # Sleep 100ms to avoid triggering a shutdown when a spike occured
sleep(2); # Sleep 2s to distinguish a long press from a short press
if (GPIO.input(PinSeven) == False):
 GPIO.output(PinEight,0) # Bring down PinEight so that the capacitor can discharge and remove power to the Pi
 call('poweroff', shell=False) # Initiate OS Poweroff
else:
 call('reboot', shell=False) # Initiate OS Reboot
```

No changes were made to the software or octopi. I´m running Octoprint V.1.4.2 and Octopi V.0.17.0

Thanks

**Comment by JLGBJ** [comment]
@shawaj  Any suggestions

Thanks

**Comment by shawaj** [comment]
@JLGBJ when you run the script directly, do you get any error messages at all?

**Comment by JLGBJ** [comment]
@shawaj Thanks for your replay, No I don’t get any error, I get this when I check the status:
pi@octopi:~ $ systemctl status piswitch.service
● piswitch.service - Starts softshut for Pi Switch
   Loaded: loaded (/etc/systemd/system/piswitch.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-10-12 11:55:26 BST; 6 days ago
 Main PID: 301 (python)
    Tasks: 1 (limit: 2077)
   Memory: 5.2M
   CGroup: /system.slice/piswitch.service
           └─301 python /opt/piswitch/softshut.py

Oct 12 11:55:26 octopi systemd[1]: Started Starts softshut for Pi Switch.

Could it be the Pi Switch it self and not the software?

Thanks

**Comment by JLGBJ** [comment]
how do you run it directly?

**Comment by JLGBJ** [comment]
@shawaj , sorted, I changed the Pi-Switch for another unit I had and it is working perfectly. Do you have any suggestions as to what component could be faulty, to see if I can repaired it?. Thanks for your help

**Comment by shawaj** [comment]
It could be the relay perhaps isn't switching correctly

**Comment by JLGBJ** [comment]
@shawaj  thanks

**Comment by shawaj** [comment]
@JLGBJ can you send me an email to sales@pi-supply.com - I think we might have some spare in the warehouse. I could send you one :-)
