### ISSUE TITLE
Upload Logo

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/Pi-Supply-Switch#9]
![pisupply-switch-logo](https://user-images.githubusercontent.com/16068311/31219700-0c1fd3e4-a9b6-11e7-8101-3b9b3c9450ad.png)

**Comment by francesco-vannini** [comment]
Use this thread to add pictures

**Comment by ChristopherRush** [comment]
![pisupply-switch-github-banner](https://user-images.githubusercontent.com/1878314/73882377-d9b49080-4859-11ea-9c7e-e3c351f821e5.png)
